"""Shared constants for Cops-and-Robbers Dec-POMDP game."""

GRID_SIZE = 7
THIEF_START_POS = (3, 3)
COP_START_POS = (0, 0)
MAX_BARRIERS = 14
MAX_MOVES = 35
SURVIVAL_THRESHOLD = 35

DEFAULT_TAU_CENTER = 0.90
DEFAULT_RHO = 0.10
SCENT_KERNEL_SIZE = 5

DEFAULT_RATE_LIMIT_RPM = 30
DEFAULT_CONCURRENT_REQUESTS = 2
DEFAULT_RETRY_BACKOFF = 5
DEFAULT_MAX_RETRIES = 3
DEFAULT_QUEUE_DEPTH = 100

SCORE_CAPTURE_COP = 20
SCORE_CAPTURE_THIEF = 5
SCORE_SURVIVAL_COP = 5
SCORE_SURVIVAL_THIEF = 10
SCORE_TIE = 2
SCORE_TECHNICAL_LOSS = 0
